version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./backend-prueba-stt
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend-stt
    restart: unless-stopped
    ports:
      - "5173:5173"

volumes:
  db_data:
